name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    name: Build and Test
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        swift: ["5.8", "5.7", "5.6"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
