name: Swift

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    name: Build and Test
    strategy:
      matrix:
        os: [macos-12, macos-11]
        swift: ["5.5"]
        xcode:
          - /Applications/Xcode_13.2.1.app
          - /Applications/Xcode_14.0.app
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: fwal/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
      - name: Set Xcode version
        run: sudo xcode-select -s "${{ matrix.xcode }}"
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
